#!/bin/bash
# Build FOL as a macOS .pkg installer
# Usage: ./build-pkg.sh
# Produces: build/Second-Self.pkg
#
# Builds the native Swift binary first, then packages into .pkg.
# The .pkg installs:
#   - /Applications/Second Self.app   (native SwiftUI app)
#   - /usr/local/share/second-self/   (Python backend services + new modules)
#   - Postinstall: Gatekeeper bypass, pip deps, .env setup

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$REPO_DIR"

APP_NAME="Second Self"
BUNDLE_ID="com.secondself.app"
VERSION="${VERSION:-$(cat "$REPO_DIR/VERSION" 2>/dev/null || echo '0.2.0')}"
BUILD_DIR="$REPO_DIR/build"
PKG_ROOT="$BUILD_DIR/pkg-root"
SCRIPTS_DIR="$BUILD_DIR/pkg-scripts"
# Check for existing app (spaced or non-spaced name)
if [ -d "$BUILD_DIR/Second Self.app" ]; then
    NATIVE_BINARY="$BUILD_DIR/Second Self.app"
elif [ -d "$BUILD_DIR/SecondSelf.app" ]; then
    NATIVE_BINARY="$BUILD_DIR/SecondSelf.app"
else
    NATIVE_BINARY="$BUILD_DIR/SecondSelf.app"
fi
PKG_FILE="$BUILD_DIR/Second-Self-$VERSION.pkg"

echo "============================================"
echo "  Building $APP_NAME v$VERSION"
echo "============================================"
echo ""

# ─── Step 1: Build native binary or verify it exists ───
if [ ! -d "$NATIVE_BINARY" ]; then
    echo "📦 Native app not found, building..."
    cd "$REPO_DIR/SecondSelf"

    # Try swift build first (preferred)
    if command -v swift &>/dev/null && swift build -c release 2>/dev/null; then
        BINARY=$(swift build -c release --show-bin-path 2>/dev/null)/SecondSelf
        if [ -f "$BINARY" ]; then
            mkdir -p "$NATIVE_BINARY/Contents/MacOS" "$NATIVE_BINARY/Contents/Resources"
            cp "$BINARY" "$NATIVE_BINARY/Contents/MacOS/SecondSelf"
            chmod +x "$NATIVE_BINARY/Contents/MacOS/SecondSelf"
            echo "  ✅ Swift build successful"
        else
            echo "  ❌ Swift binary not found — build failed"
            exit 1
        fi
    else
        echo "  ❌ Swift build failed"
        exit 1
    fi

    # Ensure Info.plist exists
    if [ ! -f "$NATIVE_BINARY/Contents/Info.plist" ]; then
        mkdir -p "$NATIVE_BINARY/Contents"
        cp "$REPO_DIR/SecondSelf/Info.plist" "$NATIVE_BINARY/Contents/Info.plist" 2>/dev/null || cat > "$NATIVE_BINARY/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key><string>SecondSelf</string>
    <key>CFBundleIdentifier</key><string>com.secondself.app</string>
    <key>CFBundleName</key><string>FOL</string>
    <key>CFBundleVersion</key><string>$VERSION</string>
    <key>CFBundleShortVersionString</key><string>$VERSION</string>
    <key>CFBundlePackageType</key><string>APPL</string>
    <key>LSMinimumSystemVersion</key><string>14.0</string>
    <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST
        echo -n 'APPL????' > "$NATIVE_BINARY/Contents/PkgInfo"
    fi
    cd "$REPO_DIR"
    echo "  ✅ Native binary ready: $(du -sh "$NATIVE_BINARY" | cut -f1)"
fi

# ─── Step 2: Clean and prepare ───
rm -rf "$PKG_ROOT" "$SCRIPTS_DIR"
mkdir -p "$PKG_ROOT/Applications"
mkdir -p "$PKG_ROOT/usr/local/share/second-self"
mkdir -p "$SCRIPTS_DIR"

# ─── Step 3: Bundle the .app ───
echo "📦 Bundling .app..."
cp -R "$NATIVE_BINARY" "$PKG_ROOT/Applications/$APP_NAME.app"

# ─── Step 4: Bundle source code to /usr/local/share/second-self/ ───
echo "📦 Bundling source code..."
# All Python modules — including new ones
for dir in orchestrator agent-server src auth fetch clean analyze \
           obsidian context_engine utils cookie_sync setup static docs fol; do
    if [ -d "$REPO_DIR/$dir" ]; then
        mkdir -p "$PKG_ROOT/usr/local/share/second-self/$dir"
        rsync -a \
            --exclude='__pycache__' \
            --exclude='*.pyc' \
            --exclude='.DS_Store' \
            --exclude='.venv' \
            --exclude='venv' \
            --exclude='htmlcov' \
            --exclude='.coverage' \
            --exclude='.pytest_cache' \
            --exclude='.ruff_cache' \
            --exclude='.mypy_cache' \
            --exclude='.build' \
            "$REPO_DIR/$dir/" "$PKG_ROOT/usr/local/share/second-self/$dir/"
    fi
done

# Root-level Python files + launcher
for f in main.py VERSION requirements.txt run_all.sh; do
    [ -f "$REPO_DIR/$f" ] && cp "$REPO_DIR/$f" "$PKG_ROOT/usr/local/share/second-self/$f"
done

# .env template
[ -f "$REPO_DIR/.env.template" ] && cp "$REPO_DIR/.env.template" "$PKG_ROOT/usr/local/share/second-self/.env.template"

# Module requirements (combine into main requirements.txt)
cat > "$PKG_ROOT/usr/local/share/second-self/requirements-all.txt" << 'REQ'
# FOL — All Python dependencies
# Auto-generated by build-pkg.sh

# Core
fastapi>=0.100.0
uvicorn>=0.23.0
python-dotenv>=1.0.0
python-multipart>=0.0.9

# LLM
anthropic>=0.30.0
litellm>=1.40.0

# Desktop automation
pyautogui>=0.9.54
Pillow>=10.0.0
pyobjc-framework-Quartz>=9.0

# Google APIs
google-api-python-client>=2.100.0
google-auth>=2.25.0
google-auth-oauthlib>=1.0.0

# Web search
tavily-python>=0.3.0

# Obsidian + memory
filelock>=3.12.0

# Auth
firebase-admin>=6.0.0
auth0-python>=4.0.0
PyJWT>=2.8.0

# FOL Engine (JARVIS-style commands)
mlx>=0.19.0
mlx-lm>=0.19.0
mlx-whisper>=0.4.0
chromadb>=0.5.5
sqlalchemy>=2.0.35
pydantic>=2.9.0
pydantic-settings>=2.5.0
websockets>=13.0
pyzmq>=26.0.0
langchain>=0.3.0
langchain-community>=0.3.0
py-applescript==1.0.3

# Future: browser-use (optional)
# browser-use[cli]>=0.1.0
REQ
echo "  ✅ Combined requirements created"

# Make scripts executable
chmod +x "$PKG_ROOT/usr/local/share/second-self/setup/"*.sh 2>/dev/null || true

# ─── Step 5: Create postinstall script ───
echo "📝 Creating postinstall script..."
cat > "$SCRIPTS_DIR/postinstall" << 'POSTINSTALL'
#!/bin/bash
# FOL — Post-install script
# Runs as root after .pkg installation.

set -e

INSTALL_DIR="/usr/local/share/second-self"
APP_DIR="/Applications/Second Self.app"
REAL_USER=$(stat -f '%Su' /dev/console 2>/dev/null || echo "")
REAL_HOME=$(dscl . -read "/Users/$REAL_USER" NFSHomeDirectory 2>/dev/null | awk '{print $2}' || echo "")
LOG="/tmp/secondself-install.log"

log() { echo "[FOL] $1" | tee -a "$LOG"; }

log "============================================"
log "  FOL v$(cat "$INSTALL_DIR/VERSION" 2>/dev/null || echo '?') — Post-install"
log "============================================"
log ""

# 1. Clear Gatekeeper quarantine
log "Clearing Gatekeeper quarantine..."
xattr -cr "$APP_DIR" 2>/dev/null || true
log "  Done"

# 2. Symlink for easy CLI access
if [ -n "$REAL_HOME" ] && [ ! -e "$REAL_HOME/second-self" ]; then
    ln -sf "$INSTALL_DIR" "$REAL_HOME/second-self"
    chown -h "$REAL_USER:staff" "$REAL_HOME/second-self" 2>/dev/null || true
    log "Symlinked ~/second-self -> $INSTALL_DIR"
fi

# 3. Create .env if it doesn't exist
ENV_FILE="$INSTALL_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
    log "Creating default .env..."
    if [ -f "$INSTALL_DIR/.env.template" ]; then
        cp "$INSTALL_DIR/.env.template" "$ENV_FILE"
    else
        cat > "$ENV_FILE" << 'ENVFILE'
# FOL — Configuration
# Get API keys and add them below

# LLM (choose one)
# LLM_MODEL=ollama/llama3.2:3b      # Local (free, needs Ollama)
LLM_MODEL=claude-sonnet-4-20250514   # Cloud (needs ANTHROPIC_API_KEY)
# LLM_MODEL=gpt-4o                    # Cloud (needs OPENAI_API_KEY)
# LLM_FALLBACK_MODELS=ollama/llama3.2:3b   # Backup models, tried if primary is unavailable

# API Keys
ANTHROPIC_API_KEY=
TAVILY_API_KEY=

# Google OAuth (for Gmail/Calendar)
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=

# Firebase (for web onboarding)
FIREBASE_API_KEY=
FIREBASE_AUTH_DOMAIN=
FIREBASE_PROJECT_ID=

# Obsidian Living Memory (optional)
OBSIDIAN_API_KEY=
OBSIDIAN_VAULT_PATH=~/Obsidian/FOL

# Server
HOST=0.0.0.0
PORT=8000
ALLOWED_ORIGINS=http://localhost:3000
ENVFILE
    fi
    chown "$REAL_USER:staff" "$ENV_FILE" 2>/dev/null || true
    log "  Default .env created (edit in $ENV_FILE)"
fi

# 4. Install Python dependencies
log "Installing Python packages..."
log "  This may take a few minutes..."

PYTHON=""
for p in "/opt/homebrew/bin/python3.12" "/opt/homebrew/bin/python3" "/usr/local/bin/python3" "/usr/bin/python3"; do
    [ -x "$p" ] && { PYTHON="$p"; break; }
done

if [ -n "$PYTHON" ]; then
    log "  Using: $PYTHON"
    $PYTHON -m pip install --break-system-packages -q \
        -r "$INSTALL_DIR/requirements-all.txt" 2>&1 | tail -3 >> "$LOG" || {
        log "  ⚠️  Some packages failed to install"
    }
    log "  Python packages installed"
else
    log "  ⚠️  Python 3 not found. Install: brew install python@3.12"
fi

log ""
log "============================================"
log "  ✅ Installation complete!"
log "============================================"
log ""
log "  Launch 'FOL' from Applications."
log "  First run may take a moment to start services."
log ""

exit 0
POSTINSTALL
chmod +x "$SCRIPTS_DIR/postinstall"
echo "  ✅ Postinstall script created"

# ─── Step 6: Build the .pkg ───
echo ""
echo "🔨 Building .pkg..."

pkgbuild \
    --root "$PKG_ROOT" \
    --scripts "$SCRIPTS_DIR" \
    --identifier "$BUNDLE_ID" \
    --version "$VERSION" \
    --install-location "/" \
    "$PKG_FILE"

# ─── Step 7: Generate checksum ───
shasum -a 256 "$PKG_FILE" > "$PKG_FILE.sha256"

PKG_SIZE=$(du -sh "$PKG_FILE" | cut -f1)
echo ""
echo "==========================================="
echo "  ✅ Built: $(basename $PKG_FILE)"
echo "  Version: $VERSION"
echo "  Size: $PKG_SIZE"
echo "  SHA256: $(cat $PKG_FILE.sha256 | cut -d' ' -f1)"
echo "==========================================="
echo ""
echo "To install:"
echo "  sudo installer -pkg \"$PKG_FILE\" -target /"
echo ""
echo "To update from old version:"
echo "  bash update.sh"
echo ""

# ─── Step 8: Cleanup build artifacts ───
rm -rf "$PKG_ROOT" "$SCRIPTS_DIR"
echo "Cleaned up temporary build files"
echo ""
