"""Asynchronous event bus for inter-module communication."""

from __future__ import annotations

import asyncio
import logging
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Callable, Coroutine
from uuid import UUID, uuid4

logger = logging.getLogger(__name__)


class EventType(Enum):
    """Types of events in the FOL system."""

    USER_INPUT_RECEIVED = auto()
    TEXT_TRANSCRIBED = auto()
    INTENT_CLASSIFIED = auto()
    LLM_RESPONSE_READY = auto()
    TOOL_EXECUTED = auto()
    MEMORY_UPDATED = auto()
    MEMORY_RETRIEVED = auto()
    STT_ERROR = auto()
    LLM_ERROR = auto()
    TOOL_ERROR = auto()
    MODULE_STATUS_CHANGED = auto()
    PLUGIN_LOADED = auto()
    PLUGIN_UNLOADED = auto()
    SYSTEM_STARTUP = auto()
    SYSTEM_SHUTDOWN = auto()
    # Proactive Mode (ROADMAP Etap 5) — a suggestion generated by the ambient
    # tick (ProactiveService). Payload: the ProactiveSuggestion as a dict.
    PROACTIVE_SUGGESTION = auto()
    PROACTIVE_TOGGLED = auto()


@dataclass
class Event:
    """Represents an event in the FOL system."""

    id: UUID = field(default_factory=uuid4)
    type: EventType = EventType.USER_INPUT_RECEIVED
    source: str = ""
    payload: dict[str, Any] = field(default_factory=dict)
    timestamp: float = 0.0
    correlation_id: UUID = field(default_factory=uuid4)

    def __post_init__(self) -> None:
        if self.timestamp == 0.0:
            import time
            self.timestamp = time.time()


EventHandler = Callable[[Event], Coroutine[Any, Any, None]]


class EventBus:
    """Asynchronous pub/sub event bus for FOL modules."""

    def __init__(self) -> None:
        self._handlers: dict[EventType, list[EventHandler]] = {}
        self._event_count: int = 0

    def subscribe(self, event_type: EventType, handler: EventHandler) -> None:
        """Subscribe a handler to a specific event type."""
        if event_type not in self._handlers:
            self._handlers[event_type] = []
        self._handlers[event_type].append(handler)
        logger.debug("Handler subscribed", event_type=event_type.name, handler=handler.__name__)

    def unsubscribe(self, event_type: EventType, handler: EventHandler) -> None:
        """Unsubscribe a handler from a specific event type."""
        if event_type in self._handlers:
            self._handlers[event_type] = [h for h in self._handlers[event_type] if h is not handler]

    async def publish(self, event: Event) -> None:
        """Publish an event to all subscribed handlers."""
        self._event_count += 1
        handlers = self._handlers.get(event.type, [])
        if not handlers:
            logger.debug("No handlers for event", event_type=event.type.name)
            return

        logger.debug(
            "Publishing event",
            event_type=event.type.name,
            source=event.source,
            handler_count=len(handlers),
        )

        for handler in handlers:
            try:
                await handler(event)
            except Exception as exc:
                logger.error(
                    "Event handler error",
                    event_type=event.type.name,
                    handler=handler.__name__,
                    error=str(exc),
                )

    def emit(
        self,
        event_type: EventType,
        source: str = "",
        payload: dict[str, Any] | None = None,
        correlation_id: UUID | None = None,
    ) -> Event:
        """Create and publish an event (convenience method).

        When called from async code the event is delivered as a background
        task; when called from sync code (no running loop — e.g. a builtin
        command handler) it is delivered synchronously on a temporary loop so
        the event is never silently dropped.
        """
        event = Event(
            type=event_type,
            source=source,
            payload=payload or {},
            correlation_id=correlation_id or uuid4(),
        )
        try:
            asyncio.get_running_loop()
        except RuntimeError:
            # No running event loop (sync caller, e.g. a builtin command) —
            # deliver inline on a temporary loop so the event is never
            # silently dropped.
            try:
                loop = asyncio.new_event_loop()
                try:
                    loop.run_until_complete(self.publish(event))
                finally:
                    loop.close()
            except Exception as exc:
                logger.debug("Event sync-emit failed: %s", exc)
        else:
            asyncio.create_task(self.publish(event))
        return event

    @property
    def event_count(self) -> int:
        """Total events published."""
        return self._event_count

    def clear(self) -> None:
        """Remove all subscriptions."""
        self._handlers.clear()
        self._event_count = 0
