#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
# FOL macOS Build Script
# Creates a native .app bundle and DMG installer
# ═══════════════════════════════════════════════════════════════════

set -e

APP_NAME="FOL"
APP_VERSION="0.1.0"
BUNDLE_NAME="FOL.app"
BUILD_DIR="build"
DIST_DIR="dist"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "🔨 Building FOL macOS App v${APP_VERSION}"
echo "═══════════════════════════════════════════"

# ─── Step 1: Clean previous builds ─────────────────────────────────
echo ""
echo "📦 Step 1: Cleaning previous builds..."
rm -rf "${SCRIPT_DIR}/${BUILD_DIR}" "${SCRIPT_DIR}/${DIST_DIR}"
mkdir -p "${SCRIPT_DIR}/${BUILD_DIR}"
mkdir -p "${SCRIPT_DIR}/${DIST_DIR}"

# ─── Step 2: Check dependencies ────────────────────────────────────
echo ""
echo "🔍 Step 2: Checking dependencies..."

# Check Python (prefer 3.12+ for PyObjC compatibility)
PYTHON_CMD=""
for cmd in python3.12 python3.13 python3; do
    if command -v "$cmd" &> /dev/null; then
        ver=$("$cmd" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
        major=$(echo "$ver" | cut -d. -f1)
        minor=$(echo "$ver" | cut -d. -f2)
        if [ "$major" -ge 3 ] && [ "$minor" -ge 12 ]; then
            PYTHON_CMD="$cmd"
            break
        fi
    fi
done

if [ -z "$PYTHON_CMD" ]; then
    echo "❌ Python 3.12+ not found. Install with: brew install python@3.12"
    exit 1
fi

PYTHON_VERSION=$("$PYTHON_CMD" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
echo "  ✓ Python ${PYTHON_VERSION} ($PYTHON_CMD)"

# Check PyObjC
"$PYTHON_CMD" -c "import AppKit" 2>/dev/null || {
    echo "  ⚠ PyObjC not found. Installing..."
    "$PYTHON_CMD" -m pip install --user pyobjc-core pyobjc-framework-Cocoa pyobjc-framework-WebKit 2>/dev/null || {
        echo "  ⚠ Trying with --break-system-packages..."
        "$PYTHON_CMD" -m pip install --user --break-system-packages pyobjc-core pyobjc-framework-Cocoa pyobjc-framework-WebKit 2>/dev/null || echo "  ⚠ PyObjC install failed. Install manually."
    }
}

# Check uvicorn
"$PYTHON_CMD" -c "import uvicorn" 2>/dev/null || {
    echo "  ⚠ uvicorn not found. Installing..."
    "$PYTHON_CMD" -m pip install --user uvicorn[standard] 2>/dev/null || true
}

echo "  ✓ All dependencies available"

# ─── Step 3: Create .app bundle structure ───────────────────────────
echo ""
echo "📂 Step 3: Creating .app bundle..."

APP_BUNDLE="${SCRIPT_DIR}/${BUILD_DIR}/${BUNDLE_NAME}"
mkdir -p "${APP_BUNDLE}/Contents/MacOS"
mkdir -p "${APP_BUNDLE}/Contents/Resources"

# ─── Step 4: Create Info.plist ──────────────────────────────────────
echo "  Creating Info.plist..."

cat > "${APP_BUNDLE}/Contents/Info.plist" << PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>com.fol.assistant</string>
    <key>CFBundleVersion</key>
    <string>${APP_VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>${APP_VERSION}</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleExecutable</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>LSMinimumSystemVersion</key>
    <string>13.0</string>
    <key>LSUIElement</key>
    <true/>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>NSSupportsAutomaticTermination</key>
    <false/>
    <key>NSMicrophoneUsageDescription</key>
    <string>FOL needs microphone access for voice input.</string>
    <key>NSAppleEventsUsageDescription</key>
    <string>FOL uses AppleScript to control applications.</string>
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsLocalNetworking</key>
        <true/>
    </dict>
    <key>NSCameraUsageDescription</key>
    <string>FOL uses the camera for avatar visualization.</string>
</dict>
</plist>
PLIST

# ─── Step 5: Create the launcher script ─────────────────────────────
echo "  Creating launcher script..."

# Find Python path
PYTHON_PATH=$(which "$PYTHON_CMD")

cat > "${APP_BUNDLE}/Contents/MacOS/${APP_NAME}" << LAUNCHER
#!/bin/bash
# FOL Launcher — starts the FOL app
# This script is auto-generated by build_mac.sh

# Get the directory of this script
DIR="\$(cd "\$(dirname "\$0")" && pwd)"
CONTENTS_DIR="\$(dirname "\$DIR")"
RESOURCES_DIR="\${CONTENTS_DIR}/Resources"

# Set up environment
export PYTHONPATH="\${RESOURCES_DIR}/fol:\$PYTHONPATH"
export FOL_DATA_DIR="\${HOME}/.fol"

# Create data directory if it doesn't exist
mkdir -p "\${FOL_DATA_DIR}"

# Check if server is already running on port 8754
if lsof -i :8754 -sTCP:LISTEN > /dev/null 2>&1; then
    echo "FOL server already running on port 8754"
    # Open the web UI in browser as fallback
    open "http://127.0.0.1:8754/"
    exit 0
fi

# Start FOL
echo "Starting FOL..."
cd "\${RESOURCES_DIR}/fol"

# Try the native Mac app first
if [ -f "fol_mac_app.py" ]; then
    "${PYTHON_PATH}" fol_mac_app.py &
    FOL_PID=\$!
else
    # Fallback to API server
    "${PYTHON_PATH}" run_api_server.py &
    FOL_PID=\$!
fi

# Wait a moment for server to start
sleep 3

# Open the web UI
open "http://127.0.0.1:8754/"

# Keep running until killed
wait \$FOL_PID
LAUNCHER

chmod +x "${APP_BUNDLE}/Contents/MacOS/${APP_NAME}"

# ─── Step 6: Bundle the FOL project ────────────────────────────────
echo "  Bundling FOL project..."

RESOURCES="${APP_BUNDLE}/Contents/Resources/fol"
mkdir -p "${RESOURCES}"

# Copy essential files
cp -r "${SCRIPT_DIR}/core" "${RESOURCES}/"
cp -r "${SCRIPT_DIR}/config" "${RESOURCES}/"
cp -r "${SCRIPT_DIR}/api" "${RESOURCES}/"
cp -r "${SCRIPT_DIR}/modules" "${RESOURCES}/"
cp -r "${SCRIPT_DIR}/plugins" "${RESOURCES}/"
cp -r "${SCRIPT_DIR}/ui" "${RESOURCES}/"
cp "${SCRIPT_DIR}/run_api_server.py" "${RESOURCES}/"
cp "${SCRIPT_DIR}/fol_mac_app.py" "${RESOURCES}/"
cp "${SCRIPT_DIR}/pyproject.toml" "${RESOURCES}/"

# ─── Step 7: Copy Python dependencies ──────────────────────────────
echo "  Copying Python dependencies..."

# Create a site-packages bundle
SITE_PACKAGES="${RESOURCES}/_site_packages"
mkdir -p "${SITE_PACKAGES}"

# Copy required packages
SITE_PACKAGES_ABS=$(cd "${SITE_PACKAGES}" && pwd)
"$PYTHON_CMD" -c "
import site, shutil, os
pkgs = ['uvicorn', 'fastapi', 'pydantic', 'starlette', 'anyio', 'httptools', 'websockets']
site_pkgs = '${SITE_PACKAGES_ABS}'
for d in site.getsitepackages() + [site.getusersitepackages()]:
    if not d: continue
    for pkg in pkgs:
        src = os.path.join(d, pkg)
        if os.path.exists(src):
            dst = os.path.join(site_pkgs, pkg)
            if not os.path.exists(dst):
                shutil.copytree(src, dst, dirs_exist_ok=True)
" 2>/dev/null || echo "  ⚠ Could not copy some dependencies"

# ─── Step 8: Copy app icon ─────────────────────────────────────────
echo "  Copying app icon..."

# Generate icon if it doesn't exist
if [ ! -f "${SCRIPT_DIR}/ui/web/AppIcon.icns" ]; then
    echo "  Generating app icon from SVG..."
    ICONSET="${SCRIPT_DIR}/ui/web/icon.iconset"
    mkdir -p "${ICONSET}"
    
    "${PYTHON_CMD}" -c "
from PIL import Image, ImageDraw, ImageFont
import os

iconset = '${ICONSET}'

def create_icon(size):
    img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    r = size // 4
    draw.rounded_rectangle([0, 0, size-1, size-1], radius=r, fill=(26, 16, 51, 255))
    cx, cy = size//2, int(size*0.51)
    rx, ry = int(size*0.195), int(size*0.205)
    for i in range(20, 0, -1):
        alpha = int(8 * (20-i)/20)
        draw.ellipse([cx-rx-i*2, cy-ry-i*2, cx+rx+i*2, cy+ry+i*2], fill=(124, 92, 255, alpha))
    bw, bh = int(size*0.156), int(size*0.171)
    draw.ellipse([cx-bw, cy-bh, cx+bw, cy+bh], fill=(124, 92, 255, 255))
    draw.ellipse([cx-int(bw*0.75), cy-int(bh*0.85), cx+int(bw*0.75), cy-int(bh*0.2)], fill=(255, 255, 255, 20))
    cr = max(1, int(size*0.035))
    draw.ellipse([cx-int(bw*0.65)-cr, cy-int(bh*0.15)-cr//2, cx-int(bw*0.65)+cr, cy-int(bh*0.15)+cr//2], fill=(248, 113, 113, 50))
    draw.ellipse([cx+int(bw*0.65)-cr, cy-int(bh*0.15)-cr//2, cx+int(bw*0.65)+cr, cy-int(bh*0.15)+cr//2], fill=(248, 113, 113, 50))
    ew, eh = max(1, int(size*0.022)), max(1, int(size*0.025))
    ey = cy - int(bh*0.2)
    draw.ellipse([cx-int(bw*0.3)-ew, ey-eh, cx-int(bw*0.3)+ew, ey+eh], fill=(10, 10, 26, 255))
    draw.ellipse([cx+int(bw*0.3)-ew, ey-eh, cx+int(bw*0.3)+ew, ey+eh], fill=(10, 10, 26, 255))
    sr = max(1, int(size*0.008))
    draw.ellipse([cx-int(bw*0.3)+ew//3-sr, ey-eh//2-sr, cx-int(bw*0.3)+ew//3+sr, ey-eh//2+sr], fill=(255, 255, 255, 217))
    draw.ellipse([cx+int(bw*0.3)+ew//3-sr, ey-eh//2-sr, cx+int(bw*0.3)+ew//3+sr, ey-eh//2+sr], fill=(255, 255, 255, 217))
    smile_y = cy + int(bh*0.15)
    smile_w = int(bw*0.55)
    draw.arc([cx-smile_w, smile_y-int(size*0.015), cx+smile_w, smile_y+int(size*0.06)], 0, 180, fill=(255, 255, 255, 178), width=max(1, size//100))
    ant_y = cy - bh - int(size*0.02)
    ant_top = cy - bh - int(size*0.06)
    draw.line([cx, ant_y, cx, ant_top], fill=(167, 139, 250, 153), width=max(1, size//100))
    ant_r = max(1, int(size*0.012))
    draw.ellipse([cx-ant_r, ant_top-ant_r, cx+ant_r, ant_top+ant_r], fill=(167, 139, 250, 178))
    if size >= 64:
        font_size = max(8, size//10)
        try:
            font = ImageFont.truetype('/System/Library/Fonts/SFNSDisplay.ttf', font_size)
        except:
            font = ImageFont.load_default()
        text = 'FOL'
        bbox = draw.textbbox((0, 0), text, font=font)
        tw = bbox[2] - bbox[0]
        if tw > 0:
            draw.text((size//2 - tw//2, int(size*0.78)), text, fill=(255, 255, 255, 230), font=font)
    return img

sizes = {
    'icon_16x16.png': 16, 'icon_16x16@2x.png': 32, 'icon_32x32.png': 32,
    'icon_32x32@2x.png': 64, 'icon_128x128.png': 128, 'icon_128x128@2x.png': 256,
    'icon_256x256.png': 256, 'icon_256x256@2x.png': 512, 'icon_512x512.png': 512,
    'icon_512x512@2x.png': 1024,
}
for name, size in sizes.items():
    create_icon(size).save(os.path.join(iconset, name))
print('Icons generated!')
" 2>/dev/null
    
    iconutil -c icns "${ICONSET}" -o "${SCRIPT_DIR}/ui/web/AppIcon.icns" 2>/dev/null
    rm -rf "${ICONSET}"
fi

# Copy icon into app bundle
if [ -f "${SCRIPT_DIR}/ui/web/AppIcon.icns" ]; then
    cp "${SCRIPT_DIR}/ui/web/AppIcon.icns" "${APP_BUNDLE}/Contents/Resources/"
    echo "  ✓ App icon included"
else
    echo "  ⚠ App icon not found"
fi

# ─── Step 9: Create PkgInfo ────────────────────────────────────────
echo "APPL????" > "${APP_BUNDLE}/Contents/PkgInfo"

# ─── Step 9: Code Sign (ad-hoc) ────────────────────────────────────
echo ""
echo "🔐 Step 9: Code signing (ad-hoc)..."

codesign --force --deep --sign - "${APP_BUNDLE}" 2>/dev/null || {
    echo "  ⚠ Code signing skipped (not critical for local use)"
}

# ─── Step 10: Create DMG installer ─────────────────────────────────
echo ""
echo "💿 Step 10: Creating DMG installer..."

DMG_NAME="FOL-${APP_VERSION}-macOS.dmg"
DMG_PATH="${SCRIPT_DIR}/${DIST_DIR}/${DMG_NAME}"

# Create a temporary directory for DMG contents
DMG_TEMP="${SCRIPT_DIR}/${BUILD_DIR}/dmg_temp"
mkdir -p "${DMG_TEMP}"

# Copy the app
cp -r "${APP_BUNDLE}" "${DMG_TEMP}/"

# Create Applications symlink
ln -s /Applications "${DMG_TEMP}/Applications"

# Create DMG
hdiutil create \
    -volname "${APP_NAME}" \
    -srcfolder "${DMG_TEMP}" \
    -ov \
    -format UDZO \
    "${DMG_PATH}" 2>/dev/null || {
    echo "  ⚠ Could not create DMG (hdiutil not available)"
    echo "  ✓ App bundle created at: ${APP_BUNDLE}"
}

# Clean up
rm -rf "${DMG_TEMP}"

echo ""
echo "═══════════════════════════════════════════"
echo "✅ Build complete!"
echo ""
echo "📦 App bundle: ${APP_BUNDLE}"
if [ -f "${DMG_PATH}" ]; then
    echo "💿 DMG installer: ${DMG_PATH}"
fi
echo ""
echo "To install:"
echo "  1. Open the DMG file"
echo "  2. Drag FOL.app to Applications"
echo "  3. Launch from Applications or Spotlight"
echo ""
echo "To run directly:"
echo "  open '${APP_BUNDLE}'"
echo "═══════════════════════════════════════════"
